"""
Django settings for GreenPrint project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

EMAIL_HOST = 'localhost'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import sys
sys.path.insert(0,"/etc/default")
import pp_settings
SECRET_KEY = pp_settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False
ADMINS = (('Matt Agresta','agresta_matt@yahoo.com'),)
MANAGERS = (('Matt Agresta','agresta_matt@yahoo.com'),)
ALLOWED_HOSTS = ['localhost']

#Redirect user login
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
#LOGIN_URL = 'django.contrib.auth.views.login'
# Application definition


